jobs:
  gather-diff-index:
    on: [pull_request]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run diff-index
        run: git diff-index -M -C ${{ github.base_ref }}

    
